"""Engine Registry — maps all 86 engine names to their classes.

Single source of truth for engine lookup. Used by the orchestrator
to instantiate and route tasks to engines.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from engines.base import BaseEngine

# Lazy imports to avoid circular dependencies and speed up startup
_ENGINE_MAP: dict[str, str] = {
    "product_selection": "engines.product_selection",
    "product_scoring": "engines.product_scoring",
    "product_validation": "engines.product_validation",
    "catalog": "engines.catalog",
    "inventory": "engines.inventory",
    "supplier": "engines.supplier",
    "market_research": "engines.market_research",
    "demand_analysis": "engines.demand_analysis",
    "competitor_analysis": "engines.competitor_analysis",
    "forecasting": "engines.forecasting",
    "pricing": "engines.pricing",
    "dynamic_pricing": "engines.dynamic_pricing",
    "monetization": "engines.monetization",
    "content_generation": "engines.content_generation",
    "creative_generation": "engines.creative_generation",
    "media": "engines.media",
    "storytelling": "engines.storytelling",
    "branding": "engines.branding",
    "marketing": "engines.marketing",
    "campaign": "engines.campaign",
    "ads": "engines.ads",
    "traffic": "engines.traffic",
    "seo": "engines.seo",
    "virality": "engines.virality",
    "funnel": "engines.funnel",
    "checkout": "engines.checkout",
    "conversion": "engines.conversion",
    "engagement": "engines.engagement",
    "retention": "engines.retention",
    "loyalty": "engines.loyalty",
    "referral": "engines.referral",
    "personalization": "engines.personalization",
    "recommendation": "engines.recommendation",
    "psychology": "engines.psychology",
    "persuasion": "engines.persuasion",
    "analytics": "engines.analytics",
    "financial": "engines.financial",
    "revenue": "engines.revenue",
    "profit": "engines.profit",
    "cost": "engines.cost",
    "investment": "engines.investment",
    "risk": "engines.risk",
    "logistics": "engines.logistics",
    "localization": "engines.localization",
    "multi_store": "engines.multi_store",
    "ecosystem": "engines.ecosystem",
    "automation": "engines.automation",
    "workflow": "engines.workflow",
    "scheduling": "engines.scheduling",
    "orchestration": "engines.orchestration",
    "execution": "engines.execution",
    "decision": "engines.decision",
    "reasoning": "engines.reasoning",
    "knowledge": "engines.knowledge",
    "planning": "engines.planning",
    "strategy": "engines.strategy",
    "simulation": "engines.simulation",
    "monitoring": "engines.monitoring",
    "anomaly_detection": "engines.anomaly_detection",
    "debugging": "engines.debugging",
    "logging": "engines.logging",
    "security": "engines.security",
    "fraud": "engines.fraud",
    "compliance": "engines.compliance",
    "governance": "engines.governance",
    "growth": "engines.growth",
    "growth_loop": "engines.growth_loop",
    "scaling": "engines.scaling",
    "ux": "engines.ux",
    "experimentation": "engines.experimentation",
    "innovation": "engines.innovation",
    "r_and_d": "engines.r_and_d",
    "meta_learning": "engines.meta_learning",
    "self_improvement": "engines.self_improvement",
    "self_evolution": "engines.self_evolution",
    "autonomous_control": "engines.autonomous_control",
    "autonomous_decision": "engines.autonomous_decision",
    "autonomous_execution": "engines.autonomous_execution",
    "autonomous_learning": "engines.autonomous_learning",
    "autonomous_scaling": "engines.autonomous_scaling",
    "meta_intelligence": "engines.meta_intelligence",
    "super_intelligence": "engines.super_intelligence",
    "agbi": "engines.agbi",
    "empire": "engines.empire",
    "civilization": "engines.civilization",
    "infinite_scaling": "engines.infinite_scaling",
    "trend_detection": "engines.trend_detection",
    "opportunity_detection": "engines.opportunity_detection",
    "opportunity_scoring": "engines.opportunity_scoring",
    "data_collection": "engines.data_collection",
    "data_enrichment": "engines.data_enrichment",
    "behavioral_data": "engines.behavioral_data",
    "user_tracking": "engines.user_tracking",
    "event_tracking": "engines.event_tracking",
    "conversion_tracking": "engines.conversion_tracking",
    "feedback_collection": "engines.feedback_collection",
    "feedback_processing": "engines.feedback_processing",
    "learning_loop": "engines.learning_loop",
    "kpi_tracking": "engines.kpi_tracking",
    "product_ranking": "engines.product_ranking",
    "product_lifecycle": "engines.product_lifecycle",
    "product_optimization": "engines.product_optimization",
    "discount_strategy": "engines.discount_strategy",
    "bundle": "engines.bundle",
    "upsell": "engines.upsell",
    "cross_sell": "engines.cross_sell",
    "cart_recovery": "engines.cart_recovery",
    "customer_segmentation": "engines.customer_segmentation",
    "audience_targeting": "engines.audience_targeting",
    "landing_page": "engines.landing_page",
    "stock_prediction": "engines.stock_prediction",
    "email_marketing": "engines.email_marketing",
    "social_media": "engines.social_media",
    "influencer": "engines.influencer",
    "affiliate": "engines.affiliate",
    "ab_testing": "engines.ab_testing",
    "price_elasticity": "engines.price_elasticity",
    "churn_prediction": "engines.churn_prediction",
    "sentiment_analysis": "engines.sentiment_analysis",
    "review_management": "engines.review_management",
    "returns_management": "engines.returns_management",
    "shipping_optimization": "engines.shipping_optimization",
    "payment_optimization": "engines.payment_optimization",
    "subscription": "engines.subscription",
    "marketplace": "engines.marketplace",
    "product_description": "engines.product_description",
    "image_optimization": "engines.image_optimization",
    "video_marketing": "engines.video_marketing",
    "chatbot": "engines.chatbot",
    "customer_support": "engines.customer_support",
    "warranty": "engines.warranty",
    "gift_card": "engines.gift_card",
    "wishlist": "engines.wishlist",
    "notification": "engines.notification",
    "search_optimization": "engines.search_optimization",
    "tag_management": "engines.tag_management",
    # Batch 3: commerce, loyalty, conversion optimization
    "tax_management": "engines.tax_management",
    "currency_conversion": "engines.currency_conversion",
    "geo_targeting": "engines.geo_targeting",
    "weather_pricing": "engines.weather_pricing",
    "seasonal_strategy": "engines.seasonal_strategy",
    "flash_sale": "engines.flash_sale",
    "pre_order": "engines.pre_order",
    "waitlist": "engines.waitlist",
    "backorder": "engines.backorder",
    "dropshipping": "engines.dropshipping",
    "wholesale": "engines.wholesale",
    "b2b_pricing": "engines.b2b_pricing",
    "contract_management": "engines.contract_management",
    "invoice_generation": "engines.invoice_generation",
    "refund_processing": "engines.refund_processing",
    "coupon_generation": "engines.coupon_generation",
    "loyalty_program": "engines.loyalty_program",
    "points_system": "engines.points_system",
    "referral_program": "engines.referral_program",
    "social_proof": "engines.social_proof",
    "urgency_creation": "engines.urgency_creation",
    "scarcity_marketing": "engines.scarcity_marketing",
    "exit_intent": "engines.exit_intent",
    "popup_optimization": "engines.popup_optimization",
    "form_optimization": "engines.form_optimization",
    # Batch 4: content, analytics, supply chain, UX
    "content_calendar": "engines.content_calendar",
    "brand_monitoring": "engines.brand_monitoring",
    "competitor_pricing": "engines.competitor_pricing",
    "market_sizing": "engines.market_sizing",
    "customer_journey": "engines.customer_journey",
    "attribution": "engines.attribution",
    "cohort_analysis": "engines.cohort_analysis",
    "ltv_prediction": "engines.ltv_prediction",
    "cac_optimization": "engines.cac_optimization",
    "margin_analysis": "engines.margin_analysis",
    "demand_forecasting": "engines.demand_forecasting",
    "supply_chain": "engines.supply_chain",
    "warehouse_optimization": "engines.warehouse_optimization",
    "delivery_optimization": "engines.delivery_optimization",
    "packaging_optimization": "engines.packaging_optimization",
    "product_photography": "engines.product_photography",
    "color_analysis": "engines.color_analysis",
    "size_recommendation": "engines.size_recommendation",
    "product_comparison": "engines.product_comparison",
    "faq_generation": "engines.faq_generation",
    "blog_generation": "engines.blog_generation",
    "translation": "engines.translation",
    "accessibility": "engines.accessibility",
    "page_speed": "engines.page_speed",
    "mobile_optimization": "engines.mobile_optimization",
    # Batch 5: UX, fraud, supply chain, sustainability
    "heat_map": "engines.heat_map",
    "user_flow": "engines.user_flow",
    "cart_analysis": "engines.cart_analysis",
    "checkout_optimization": "engines.checkout_optimization",
    "order_routing": "engines.order_routing",
    "fraud_scoring": "engines.fraud_scoring",
    "identity_verification": "engines.identity_verification",
    "dispute_resolution": "engines.dispute_resolution",
    "vendor_scoring": "engines.vendor_scoring",
    "procurement": "engines.procurement",
    "quality_control": "engines.quality_control",
    "returns_prediction": "engines.returns_prediction",
    "cross_border": "engines.cross_border",
    "customs_management": "engines.customs_management",
    "sustainability": "engines.sustainability",
    "carbon_tracking": "engines.carbon_tracking",
    "ethical_sourcing": "engines.ethical_sourcing",
    "customer_health": "engines.customer_health",
    "nps_tracking": "engines.nps_tracking",
    "voice_of_customer": "engines.voice_of_customer",
    "product_bundling_ai": "engines.product_bundling_ai",
    "dynamic_collection": "engines.dynamic_collection",
    "visual_merchandising": "engines.visual_merchandising",
    "price_testing": "engines.price_testing",
    "revenue_forecasting": "engines.revenue_forecasting",
    # Batch 6: finance, analytics, compliance, integrations
    "expense_tracking": "engines.expense_tracking",
    "cash_flow": "engines.cash_flow",
    "profit_margin": "engines.profit_margin",
    "tax_optimization": "engines.tax_optimization",
    "store_analytics": "engines.store_analytics",
    "product_analytics": "engines.product_analytics",
    "customer_analytics": "engines.customer_analytics",
    "marketing_analytics": "engines.marketing_analytics",
    "inventory_alerts": "engines.inventory_alerts",
    "price_monitoring": "engines.price_monitoring",
    "compliance_checker": "engines.compliance_checker",
    "gdpr_management": "engines.gdpr_management",
    "cookie_consent": "engines.cookie_consent",
    "data_export": "engines.data_export",
    "report_generation": "engines.report_generation",
    "dashboard_creation": "engines.dashboard_creation",
    "webhook_management": "engines.webhook_management",
    "api_integration": "engines.api_integration",
    "data_sync": "engines.data_sync",
    "backup_management": "engines.backup_management",
    "theme_optimization": "engines.theme_optimization",
    "app_recommendation": "engines.app_recommendation",
    "staff_management": "engines.staff_management",
    "multi_channel": "engines.multi_channel",
    "pos_integration": "engines.pos_integration",
    # Batch 7: marketing channels, SEO, community, intelligence
    "sms_marketing": "engines.sms_marketing",
    "push_notification": "engines.push_notification",
    "product_feed": "engines.product_feed",
    "sitemap_generation": "engines.sitemap_generation",
    "structured_data": "engines.structured_data",
    "link_building": "engines.link_building",
    "keyword_research": "engines.keyword_research",
    "content_gap": "engines.content_gap",
    "social_listening": "engines.social_listening",
    "ugc_management": "engines.ugc_management",
    "community_management": "engines.community_management",
    "event_marketing": "engines.event_marketing",
    "seasonal_promotion": "engines.seasonal_promotion",
    "win_back": "engines.win_back",
    "vip_management": "engines.vip_management",
    "product_launch": "engines.product_launch",
    "brand_voice": "engines.brand_voice",
    "competitor_tracking": "engines.competitor_tracking",
    "market_intelligence": "engines.market_intelligence",
    "pricing_intelligence": "engines.pricing_intelligence",
}

_engine_cache: dict[str, BaseEngine] = {}


def get_engine(name: str) -> BaseEngine:
    """Get an engine instance by name (cached)."""
    if name in _engine_cache:
        return _engine_cache[name]

    if name not in _ENGINE_MAP:
        raise KeyError(f"Unknown engine: {name}")

    import importlib
    module = importlib.import_module(_ENGINE_MAP[name])

    # Convention: class name is CamelCase of engine name + "Engine"
    words = name.split("_")
    class_name = "".join(w.capitalize() for w in words) + "Engine"
    engine_class = getattr(module, class_name)
    instance = engine_class()
    _engine_cache[name] = instance
    return instance


def list_engines() -> list[str]:
    """Return all registered engine names."""
    return sorted(_ENGINE_MAP.keys())


def engine_count() -> int:
    """Return total number of registered engines."""
    return len(_ENGINE_MAP)
