"""EU AI Act Article 50 compliance gate (Aug 2 2026).

Wave A-4 of IMPLEMENTATION_PLAN_2026. Per EU AI Act Article 50,
deployers of generative AI for image / audio / video must:

  1. Embed machine-readable provenance metadata (C2PA is the
     de-facto standard referenced in the Dec 2025 EC draft Code
     of Practice).
  2. Display visible disclosure that content is AI-generated
     when used for deepfakes / consumer-facing impressions.
  3. Maintain an audit trail that enforcement bodies can
     inspect.

Fines: up to 3% of global turnover for violations.

This module is a **gate** — every AI-generated creative bound
for an EU-targeted channel passes through ``verify()``. The
gate returns a verdict: pass (compliant) / block (caller must
fix) / advisory (non-EU market, but we still log).

Separate from actual C2PA *signing* (which typically happens
inside the generation provider — fal.ai, Higgsfield, Runway
all emit C2PA manifests in 2026). This module *verifies* the
manifest + the disclosure text + writes the audit row.

Pure stdlib. LLM-free. Deterministic given inputs.

Sources:
  * artificialintelligenceact.eu/article/50/
  * digital-strategy.ec.europa.eu (Dec 2025 draft Code of
    Practice on AI labelling and transparency)
  * c2pa.org (Content Provenance and Authenticity coalition)
"""
from __future__ import annotations

import hashlib
import json
import os
import threading
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from utils.logger import get_logger


logger = get_logger("execution.compliance.eu_ai_act_gate")


_EU_REGIONS: frozenset[str] = frozenset({
    "EU",
    "AT", "BE", "BG", "HR", "CY", "CZ", "DK", "EE", "FI",
    "FR", "DE", "GR", "HU", "IE", "IT", "LV", "LT", "LU",
    "MT", "NL", "PL", "PT", "RO", "SK", "SI", "ES", "SE",
})

# Minimal disclosure text accepted — must be human-readable and
# localized per market; this module validates presence, not
# translation quality.
_DISCLOSURE_MIN_LENGTH = 6

# Canonical disclosure substrings (case-insensitive). Adding a
# new language or variant is a config-only change — no code
# release needed.
_DISCLOSURE_TOKENS: tuple[str, ...] = (
    "ai-generated",
    "ai generated",
    "generated by ai",
    "ai content",
    "künstliche intelligenz",  # de
    "contenido generado por ia",  # es
    "contenu généré par ia",  # fr
    "contenuto generato da ia",  # it
    "treść wygenerowana przez ai",  # pl
    "ai által létrehozott",  # hu
    "by ai",
)


@dataclass
class C2PAManifest:
    """Subset of C2PA claim fields we require.

    The full C2PA spec has many more optional fields; we verify
    only the minimum Article 50 disclosure bundle.
    """
    creator: str
    generator_model: str
    created_at_iso: str
    ai_generated: bool
    signature: str = ""
    media_hash: str = ""

    def as_dict(self) -> dict[str, Any]:
        return {
            "creator": self.creator,
            "generator_model": self.generator_model,
            "created_at_iso": self.created_at_iso,
            "ai_generated": self.ai_generated,
            "signature": self.signature,
            "media_hash": self.media_hash,
        }


@dataclass
class Creative:
    """Minimal creative shape the gate needs to verify."""
    asset_id: str
    media_kind: str                # image | video | audio
    c2pa: C2PAManifest | None = None
    disclosure_text: str = ""
    target_markets: tuple[str, ...] = ()
    media_bytes_sample: bytes = b""  # for optional hash verify

    def as_dict(self) -> dict[str, Any]:
        return {
            "asset_id": self.asset_id,
            "media_kind": self.media_kind,
            "c2pa": (
                self.c2pa.as_dict()
                if self.c2pa else None
            ),
            "disclosure_text": self.disclosure_text,
            "target_markets": list(self.target_markets),
        }


@dataclass
class GateVerdict:
    asset_id: str
    decision: str                  # pass | block | advisory
    reason: str
    eu_targeted: bool
    audit_path: str = ""
    missing: tuple[str, ...] = field(default_factory=tuple)

    def as_dict(self) -> dict[str, Any]:
        return {
            "asset_id": self.asset_id,
            "decision": self.decision,
            "reason": self.reason,
            "eu_targeted": self.eu_targeted,
            "audit_path": self.audit_path,
            "missing": list(self.missing),
        }


class EUAIActGate:
    """Gate every AI-generated creative before ad upload."""

    def __init__(
        self,
        *,
        vault_decisions_dir: str | Path = "vault/Decisions",
        required_for_all_markets: bool = False,
        now_fn: Any = None,
    ) -> None:
        self._dir = Path(vault_decisions_dir)
        self._dir.mkdir(parents=True, exist_ok=True)
        self._all_markets = bool(required_for_all_markets)
        self._now_fn = now_fn or time.time
        self._lock = threading.RLock()
        self._blocked_count = 0
        self._passed_count = 0

    # ── Verification ────────────────────────────────────

    @staticmethod
    def is_eu_target(markets: tuple[str, ...]) -> bool:
        if not markets:
            return False
        return any(
            m.upper() in _EU_REGIONS for m in markets
        )

    @staticmethod
    def validate_disclosure(text: str) -> bool:
        if not text:
            return False
        if len(text.strip()) < _DISCLOSURE_MIN_LENGTH:
            return False
        low = text.lower()
        return any(
            token in low for token in _DISCLOSURE_TOKENS
        )

    @staticmethod
    def validate_c2pa(
        c2pa: C2PAManifest | None,
    ) -> tuple[bool, str]:
        if c2pa is None:
            return False, "c2pa manifest missing"
        if not c2pa.ai_generated:
            return False, "c2pa.ai_generated=false"
        if not c2pa.generator_model:
            return False, "c2pa.generator_model missing"
        if not c2pa.created_at_iso:
            return False, "c2pa.created_at_iso missing"
        return True, ""

    @staticmethod
    def verify_media_hash(
        c2pa: C2PAManifest,
        media_sample: bytes,
    ) -> bool:
        """Optional tamper check. Returns True when the sample
        matches the manifest hash, or when the caller didn't
        provide a hash to check against."""
        if not c2pa.media_hash:
            return True
        if not media_sample:
            return True
        computed = hashlib.sha256(
            media_sample,
        ).hexdigest()
        return computed == c2pa.media_hash.lower()

    # ── Gate entry ──────────────────────────────────────

    def verify(self, creative: Creative) -> GateVerdict:
        if not isinstance(creative, Creative):
            raise TypeError(
                "creative must be a Creative instance",
            )
        eu_target = self.is_eu_target(creative.target_markets)
        enforce = eu_target or self._all_markets
        missing: list[str] = []
        c2pa_ok, c2pa_note = self.validate_c2pa(
            creative.c2pa,
        )
        if not c2pa_ok:
            missing.append(c2pa_note)
        if not self.validate_disclosure(
            creative.disclosure_text,
        ):
            missing.append("disclosure_text missing or too short")
        if creative.c2pa is not None and not self.verify_media_hash(
            creative.c2pa, creative.media_bytes_sample,
        ):
            missing.append(
                "media_hash mismatch — possible tampering",
            )
        if missing:
            decision = "block" if enforce else "advisory"
            reason = (
                f"EU-targeted creative missing: "
                + "; ".join(missing)
                if enforce
                else (
                    "non-EU market — logged but not blocked: "
                    + "; ".join(missing)
                )
            )
        else:
            decision = "pass"
            reason = "compliant"

        audit_path = self._write_audit(
            creative=creative,
            decision=decision,
            reason=reason,
            eu_target=eu_target,
            missing=missing,
        )
        with self._lock:
            if decision == "block":
                self._blocked_count += 1
            elif decision == "pass":
                self._passed_count += 1
        return GateVerdict(
            asset_id=creative.asset_id,
            decision=decision,
            reason=reason,
            eu_targeted=eu_target,
            audit_path=audit_path,
            missing=tuple(missing),
        )

    # ── Audit ────────────────────────────────────────────

    def _write_audit(
        self,
        *,
        creative: Creative,
        decision: str,
        reason: str,
        eu_target: bool,
        missing: list[str],
    ) -> str:
        now = float(self._now_fn())
        stamp = time.strftime(
            "%Y-%m-%dT%H-%M-%SZ",
            time.gmtime(now),
        )
        safe_id = "".join(
            ch if ch.isalnum() or ch in "-_"
            else "_"
            for ch in creative.asset_id[:40]
        ) or "unnamed"
        fname = f"{stamp}_{safe_id}_{decision}.md"
        path = self._dir / fname
        body = [
            f"# EU AI Act gate — {creative.asset_id}",
            "",
            f"- timestamp: {stamp}",
            f"- decision: **{decision}**",
            f"- reason: {reason}",
            f"- eu_targeted: {eu_target}",
            f"- media_kind: {creative.media_kind}",
            f"- target_markets: "
            f"{', '.join(creative.target_markets) or '(none)'}",
        ]
        if creative.c2pa is not None:
            body.append(
                "- c2pa: "
                + json.dumps(creative.c2pa.as_dict()),
            )
        if missing:
            body.append("- missing: " + "; ".join(missing))
        try:
            path.write_text(
                "\n".join(body), encoding="utf-8",
            )
        except Exception as exc:  # noqa: BLE001
            logger.debug(
                "audit write failed for %s: %s",
                path, exc,
            )
            return ""
        return str(path)

    # ── Diagnostics ─────────────────────────────────────

    def stats(self) -> dict[str, Any]:
        with self._lock:
            return {
                "blocked": self._blocked_count,
                "passed": self._passed_count,
                "vault_dir": str(self._dir),
                "required_for_all_markets": (
                    self._all_markets
                ),
            }


# ── Singleton ───────────────────────────────────────────────

_SINGLETON: EUAIActGate | None = None
_SINGLETON_LOCK = threading.Lock()


def get_eu_ai_gate() -> EUAIActGate:
    global _SINGLETON
    if _SINGLETON is None:
        with _SINGLETON_LOCK:
            if _SINGLETON is None:
                _SINGLETON = EUAIActGate()
    return _SINGLETON


def reset_eu_ai_gate_for_tests() -> None:
    global _SINGLETON
    with _SINGLETON_LOCK:
        _SINGLETON = None
