"""Reference data for narrative generation.

Templates per decision type, transition phrases, score descriptors,
and formatting rules used by the narrative builder module.
"""

from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------------------
# Score descriptors — maps minimum score to human-readable label
# ---------------------------------------------------------------------------
SCORE_DESCRIPTORS: dict[int, str] = {
    80: "excellent",
    65: "strong",
    50: "solid",
    35: "moderate",
    20: "weak",
    0: "very weak",
}

# ---------------------------------------------------------------------------
# Risk descriptors — maps risk level to readable phrase
# ---------------------------------------------------------------------------
RISK_DESCRIPTORS: dict[str, str] = {
    "critical": "critical risk — significant chance of loss",
    "high": "high risk — proceed with caution and tight stop-losses",
    "moderate": "moderate risk — manageable with proper mitigation",
    "low": "low risk — favorable conditions with standard precautions",
    "minimal": "minimal risk — strong fundamentals across all dimensions",
    "unknown": "unknown risk — insufficient data to assess",
}

# ---------------------------------------------------------------------------
# Confidence descriptors
# ---------------------------------------------------------------------------
CONFIDENCE_DESCRIPTORS: dict[str, str] = {
    "high": "high confidence backed by comprehensive data",
    "moderate": "moderate confidence with some data gaps",
    "low": "low confidence — critical data is missing",
    "unknown": "unknown confidence level",
}

# ---------------------------------------------------------------------------
# Narrative templates by section
# ---------------------------------------------------------------------------
NARRATIVE_TEMPLATES: dict[str, Any] = {
    "summary": {
        "profit": (
            "We recommend {product_name} (score: {score}/100, {score_desc}) "
            "as the top profit-optimized selection with {risk_desc} and {conf_desc}."
        ),
        "growth": (
            "We recommend {product_name} (score: {score}/100, {score_desc}) "
            "as the top growth-optimized selection with {risk_desc} and {conf_desc}."
        ),
        "balanced": (
            "We recommend {product_name} (score: {score}/100, {score_desc}) "
            "as the top balanced selection with {risk_desc} and {conf_desc}."
        ),
    },
    "what": (
        "{product_name} scored {score}/100 after evaluating {alt_count} "
        "alternative products. It offers a projected margin of {margin}% "
        "and a demand score of {demand_score}/100, making it the strongest "
        "candidate in this evaluation."
    ),
    "why": {
        "profit": (
            "This product was selected because it maximizes profitability. "
            "With a {margin}% margin and a {score}/100 unified score, it "
            "outperforms alternatives on the metrics that matter most for "
            "your profit-focused goal. The risk profile is {risk_desc}, and "
            "our analysis has {conf_desc}."
        ),
        "growth": (
            "This product was selected for its growth potential. "
            "With a {score}/100 unified score and strong demand signals, it "
            "aligns with your growth-focused strategy. The risk profile is "
            "{risk_desc}, and our analysis has {conf_desc}."
        ),
        "balanced": (
            "This product was selected for its well-rounded performance. "
            "Scoring {score}/100 across profitability, demand, competition, "
            "and risk dimensions, it represents the best all-around choice. "
            "The risk profile is {risk_desc}, and our analysis has {conf_desc}."
        ),
    },
    "how": (
        "This recommendation was generated by analyzing data from {engine_count} "
        "specialized engines covering {coverage}% of our evaluation criteria. "
        "Each engine independently assessed {product_name} on its own dimension, "
        "and the scores were aggregated using goal-weighted normalization. "
        "The risk level ({risk_level}) was applied as a multiplier to ensure "
        "high-risk products are not overvalued."
    ),
}

# ---------------------------------------------------------------------------
# Transition phrases between narrative sections
# ---------------------------------------------------------------------------
TRANSITION_PHRASES: dict[str, str] = {
    "what": "Here is what we found:",
    "why": "The reasoning behind this selection is clear.",
    "how": "This conclusion was reached through a systematic process.",
    "risk": "However, it is important to consider the risks.",
    "alternatives": "Other products were also evaluated.",
    "action": "To move forward, here are the recommended next steps.",
}

# ---------------------------------------------------------------------------
# Formatting rules
# ---------------------------------------------------------------------------
FORMATTING_RULES: dict[str, Any] = {
    "max_words": 500,
    "min_key_points": 3,
    "max_key_points": 10,
    "paragraph_separator": "\n\n",
    "bullet_prefix": "  - ",
    "number_format": "Use specific numbers, not vague adjectives",
    "tone": "Professional, balanced, data-driven",
}
